# Default values for acceleration-calc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

acceleration_dv:
    name: "acceleration-dv"
    image:
      repository: andrenarciso4/acceleration-dv
      tag: 0.0.1
      pullPolicy: IfNotPresent 
      
    service:
      type: ClusterIP
      port: 3001

acceleration_a:
    name: "acceleration-a"
    image:
      repository: andrenarciso4/acceleration-a
      tag: 0.0.1
      pullPolicy: IfNotPresent
      
    service:
      type: ClusterIP
      port: 3002

acceleration_calc:
    name: "acceleration-calc"
    image:
      repository: andrenarciso4/acceleration-calc
      tag: 0.0.1
      pullPolicy: IfNotPresent 
      
    service:
      type: LoadBalancer
      port: 80
      targetPort: 3000
      
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
